package internal

import (
	"context"

	"github.com/nimaeskandary/go-realworld/cmd/http_server/app/http_handler/internal/routes"
	"github.com/nimaeskandary/go-realworld/pkg/api_gen"
)

// generatedRoutesImpl implements the autogenerated api_gen.StrictServerInterface. It is just a thin wrapper that delegates to the actual handler implementations
type generatedRoutesImpl struct {
	profileRoutes *routes.ProfileRoutes
	userRoutes    *routes.UserRoutes
}

func NewGeneratedRoutesImpl(
	profileRoutes *routes.ProfileRoutes,
	userRoutes *routes.UserRoutes,
) api_gen.StrictServerInterface {
	return &generatedRoutesImpl{
		profileRoutes: profileRoutes,
		userRoutes:    userRoutes,
	}
}

func (r *generatedRoutesImpl) GetArticles(ctx context.Context, request api_gen.GetArticlesRequestObject) (api_gen.GetArticlesResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) CreateArticle(ctx context.Context, request api_gen.CreateArticleRequestObject) (api_gen.CreateArticleResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) GetArticlesFeed(ctx context.Context, request api_gen.GetArticlesFeedRequestObject) (api_gen.GetArticlesFeedResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) DeleteArticle(ctx context.Context, request api_gen.DeleteArticleRequestObject) (api_gen.DeleteArticleResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) GetArticle(ctx context.Context, request api_gen.GetArticleRequestObject) (api_gen.GetArticleResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) UpdateArticle(ctx context.Context, request api_gen.UpdateArticleRequestObject) (api_gen.UpdateArticleResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) GetArticleComments(ctx context.Context, request api_gen.GetArticleCommentsRequestObject) (api_gen.GetArticleCommentsResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) CreateArticleComment(ctx context.Context, request api_gen.CreateArticleCommentRequestObject) (api_gen.CreateArticleCommentResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) DeleteArticleComment(ctx context.Context, request api_gen.DeleteArticleCommentRequestObject) (api_gen.DeleteArticleCommentResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) DeleteArticleFavorite(ctx context.Context, request api_gen.DeleteArticleFavoriteRequestObject) (api_gen.DeleteArticleFavoriteResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) CreateArticleFavorite(ctx context.Context, request api_gen.CreateArticleFavoriteRequestObject) (api_gen.CreateArticleFavoriteResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) GetProfileByUsername(ctx context.Context, request api_gen.GetProfileByUsernameRequestObject) (api_gen.GetProfileByUsernameResponseObject, error) {
	return r.profileRoutes.GetProfileByUsername(ctx, request)
}

func (r *generatedRoutesImpl) UnfollowUserByUsername(ctx context.Context, request api_gen.UnfollowUserByUsernameRequestObject) (api_gen.UnfollowUserByUsernameResponseObject, error) {
	return r.profileRoutes.UnfollowUserByUsername(ctx, request)
}

func (r *generatedRoutesImpl) FollowUserByUsername(ctx context.Context, request api_gen.FollowUserByUsernameRequestObject) (api_gen.FollowUserByUsernameResponseObject, error) {
	return r.profileRoutes.FollowUserByUsername(ctx, request)
}

func (r *generatedRoutesImpl) GetTags(ctx context.Context, request api_gen.GetTagsRequestObject) (api_gen.GetTagsResponseObject, error) {
	return nil, nil
}

func (r *generatedRoutesImpl) GetCurrentUser(ctx context.Context, request api_gen.GetCurrentUserRequestObject) (api_gen.GetCurrentUserResponseObject, error) {
	return r.userRoutes.GetCurrentUser(ctx, request)
}

func (r *generatedRoutesImpl) UpdateCurrentUser(ctx context.Context, request api_gen.UpdateCurrentUserRequestObject) (api_gen.UpdateCurrentUserResponseObject, error) {
	return r.userRoutes.UpdateCurrentUser(ctx, request)
}

func (r *generatedRoutesImpl) CreateUser(ctx context.Context, request api_gen.CreateUserRequestObject) (api_gen.CreateUserResponseObject, error) {
	return r.userRoutes.CreateUser(ctx, request)
}

func (r *generatedRoutesImpl) Login(ctx context.Context, request api_gen.LoginRequestObject) (api_gen.LoginResponseObject, error) {
	return r.userRoutes.Login(ctx, request)
}
