// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package obs_types_mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// CtxWithLogAttributes provides a mock function for the type MockLogger
func (_mock *MockLogger) CtxWithLogAttributes(ctx context.Context, attributes ...any) context.Context {
	var tmpRet mock.Arguments
	if len(attributes) > 0 {
		tmpRet = _mock.Called(ctx, attributes)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CtxWithLogAttributes")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...any) context.Context); ok {
		r0 = returnFunc(ctx, attributes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockLogger_CtxWithLogAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CtxWithLogAttributes'
type MockLogger_CtxWithLogAttributes_Call struct {
	*mock.Call
}

// CtxWithLogAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - attributes ...any
func (_e *MockLogger_Expecter) CtxWithLogAttributes(ctx interface{}, attributes ...interface{}) *MockLogger_CtxWithLogAttributes_Call {
	return &MockLogger_CtxWithLogAttributes_Call{Call: _e.mock.On("CtxWithLogAttributes",
		append([]interface{}{ctx}, attributes...)...)}
}

func (_c *MockLogger_CtxWithLogAttributes_Call) Run(run func(ctx context.Context, attributes ...any)) *MockLogger_CtxWithLogAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []any
		var variadicArgs []any
		if len(args) > 1 {
			variadicArgs = args[1].([]any)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_CtxWithLogAttributes_Call) Return(context1 context.Context) *MockLogger_CtxWithLogAttributes_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockLogger_CtxWithLogAttributes_Call) RunAndReturn(run func(ctx context.Context, attributes ...any) context.Context) *MockLogger_CtxWithLogAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(ctx context.Context, msg string, err error, attributes ...any) {
	if len(attributes) > 0 {
		_mock.Called(ctx, msg, err, attributes)
	} else {
		_mock.Called(ctx, msg, err)
	}

	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - err error
//   - attributes ...any
func (_e *MockLogger_Expecter) Error(ctx interface{}, msg interface{}, err interface{}, attributes ...interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{ctx, msg, err}, attributes...)...)}
}

func (_c *MockLogger_Error_Call) Run(run func(ctx context.Context, msg string, err error, attributes ...any)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(ctx context.Context, msg string, err error, attributes ...any)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(ctx context.Context, msg string, attributes ...any) {
	if len(attributes) > 0 {
		_mock.Called(ctx, msg, attributes)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - attributes ...any
func (_e *MockLogger_Expecter) Info(ctx interface{}, msg interface{}, attributes ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{ctx, msg}, attributes...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(ctx context.Context, msg string, attributes ...any)) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(ctx context.Context, msg string, attributes ...any)) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}
