// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package config_types_mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretParser creates a new instance of MockSecretParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretParser {
	mock := &MockSecretParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretParser is an autogenerated mock type for the SecretParser type
type MockSecretParser struct {
	mock.Mock
}

type MockSecretParser_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretParser) EXPECT() *MockSecretParser_Expecter {
	return &MockSecretParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type MockSecretParser
func (_mock *MockSecretParser) Parse(raw string) (string, error) {
	ret := _mock.Called(raw)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(raw)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(raw)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(raw)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type MockSecretParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - raw string
func (_e *MockSecretParser_Expecter) Parse(raw interface{}) *MockSecretParser_Parse_Call {
	return &MockSecretParser_Parse_Call{Call: _e.mock.On("Parse", raw)}
}

func (_c *MockSecretParser_Parse_Call) Run(run func(raw string)) *MockSecretParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSecretParser_Parse_Call) Return(s string, err error) *MockSecretParser_Parse_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecretParser_Parse_Call) RunAndReturn(run func(raw string) (string, error)) *MockSecretParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
