// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_types_mocks

import (
	"context"
	"time"

	"github.com/nimaeskandary/go-realworld/pkg/auth/types"
	"github.com/nimaeskandary/go-realworld/pkg/user/types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthToken creates a new instance of MockAuthToken. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthToken(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthToken {
	mock := &MockAuthToken{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthToken is an autogenerated mock type for the AuthToken type
type MockAuthToken struct {
	mock.Mock
}

type MockAuthToken_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthToken) EXPECT() *MockAuthToken_Expecter {
	return &MockAuthToken_Expecter{mock: &_m.Mock}
}

// GetTTL provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) GetTTL() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTTL")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockAuthToken_GetTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTTL'
type MockAuthToken_GetTTL_Call struct {
	*mock.Call
}

// GetTTL is a helper method to define mock.On call
func (_e *MockAuthToken_Expecter) GetTTL() *MockAuthToken_GetTTL_Call {
	return &MockAuthToken_GetTTL_Call{Call: _e.mock.On("GetTTL")}
}

func (_c *MockAuthToken_GetTTL_Call) Run(run func()) *MockAuthToken_GetTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthToken_GetTTL_Call) Return(duration time.Duration) *MockAuthToken_GetTTL_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockAuthToken_GetTTL_Call) RunAndReturn(run func() time.Duration) *MockAuthToken_GetTTL_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenString provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) GetTokenString() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTokenString")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockAuthToken_GetTokenString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenString'
type MockAuthToken_GetTokenString_Call struct {
	*mock.Call
}

// GetTokenString is a helper method to define mock.On call
func (_e *MockAuthToken_Expecter) GetTokenString() *MockAuthToken_GetTokenString_Call {
	return &MockAuthToken_GetTokenString_Call{Call: _e.mock.On("GetTokenString")}
}

func (_c *MockAuthToken_GetTokenString_Call) Run(run func()) *MockAuthToken_GetTokenString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthToken_GetTokenString_Call) Return(s string) *MockAuthToken_GetTokenString_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockAuthToken_GetTokenString_Call) RunAndReturn(run func() string) *MockAuthToken_GetTokenString_Call {
	_c.Call.Return(run)
	return _c
}

// GetUser provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) GetUser() user_types.User {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 user_types.User
	if returnFunc, ok := ret.Get(0).(func() user_types.User); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(user_types.User)
	}
	return r0
}

// MockAuthToken_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthToken_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
func (_e *MockAuthToken_Expecter) GetUser() *MockAuthToken_GetUser_Call {
	return &MockAuthToken_GetUser_Call{Call: _e.mock.On("GetUser")}
}

func (_c *MockAuthToken_GetUser_Call) Run(run func()) *MockAuthToken_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthToken_GetUser_Call) Return(user user_types.User) *MockAuthToken_GetUser_Call {
	_c.Call.Return(user)
	return _c
}

func (_c *MockAuthToken_GetUser_Call) RunAndReturn(run func() user_types.User) *MockAuthToken_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// IsExpired provides a mock function for the type MockAuthToken
func (_mock *MockAuthToken) IsExpired() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsExpired")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockAuthToken_IsExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExpired'
type MockAuthToken_IsExpired_Call struct {
	*mock.Call
}

// IsExpired is a helper method to define mock.On call
func (_e *MockAuthToken_Expecter) IsExpired() *MockAuthToken_IsExpired_Call {
	return &MockAuthToken_IsExpired_Call{Call: _e.mock.On("IsExpired")}
}

func (_c *MockAuthToken_IsExpired_Call) Run(run func()) *MockAuthToken_IsExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAuthToken_IsExpired_Call) Return(b bool) *MockAuthToken_IsExpired_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockAuthToken_IsExpired_Call) RunAndReturn(run func() bool) *MockAuthToken_IsExpired_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GenerateToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GenerateToken(ctx context.Context, username string) (auth_types.AuthToken, auth_types.DomainError) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GenerateToken")
	}

	var r0 auth_types.AuthToken
	var r1 auth_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth_types.AuthToken, auth_types.DomainError)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth_types.AuthToken); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth_types.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) auth_types.DomainError); ok {
		r1 = returnFunc(ctx, username)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(auth_types.DomainError)
		}
	}
	return r0, r1
}

// MockAuthService_GenerateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateToken'
type MockAuthService_GenerateToken_Call struct {
	*mock.Call
}

// GenerateToken is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockAuthService_Expecter) GenerateToken(ctx interface{}, username interface{}) *MockAuthService_GenerateToken_Call {
	return &MockAuthService_GenerateToken_Call{Call: _e.mock.On("GenerateToken", ctx, username)}
}

func (_c *MockAuthService_GenerateToken_Call) Run(run func(ctx context.Context, username string)) *MockAuthService_GenerateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_GenerateToken_Call) Return(authToken auth_types.AuthToken, domainError auth_types.DomainError) *MockAuthService_GenerateToken_Call {
	_c.Call.Return(authToken, domainError)
	return _c
}

func (_c *MockAuthService_GenerateToken_Call) RunAndReturn(run func(ctx context.Context, username string) (auth_types.AuthToken, auth_types.DomainError)) *MockAuthService_GenerateToken_Call {
	_c.Call.Return(run)
	return _c
}

// ParseToken provides a mock function for the type MockAuthService
func (_mock *MockAuthService) ParseToken(ctx context.Context, token string) (auth_types.AuthToken, auth_types.DomainError) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for ParseToken")
	}

	var r0 auth_types.AuthToken
	var r1 auth_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (auth_types.AuthToken, auth_types.DomainError)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) auth_types.AuthToken); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(auth_types.AuthToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) auth_types.DomainError); ok {
		r1 = returnFunc(ctx, token)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(auth_types.DomainError)
		}
	}
	return r0, r1
}

// MockAuthService_ParseToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseToken'
type MockAuthService_ParseToken_Call struct {
	*mock.Call
}

// ParseToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthService_Expecter) ParseToken(ctx interface{}, token interface{}) *MockAuthService_ParseToken_Call {
	return &MockAuthService_ParseToken_Call{Call: _e.mock.On("ParseToken", ctx, token)}
}

func (_c *MockAuthService_ParseToken_Call) Run(run func(ctx context.Context, token string)) *MockAuthService_ParseToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthService_ParseToken_Call) Return(authToken auth_types.AuthToken, domainError auth_types.DomainError) *MockAuthService_ParseToken_Call {
	_c.Call.Return(authToken, domainError)
	return _c
}

func (_c *MockAuthService_ParseToken_Call) RunAndReturn(run func(ctx context.Context, token string) (auth_types.AuthToken, auth_types.DomainError)) *MockAuthService_ParseToken_Call {
	_c.Call.Return(run)
	return _c
}
