// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package user_types_mocks

import (
	"context"

	"github.com/google/uuid"
	"github.com/nimaeskandary/go-realworld/pkg/user/types"
	"github.com/samber/mo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DeleteUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DeleteUser(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_DeleteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUser'
type MockUserRepository_DeleteUser_Call struct {
	*mock.Call
}

// DeleteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) DeleteUser(ctx interface{}, id interface{}) *MockUserRepository_DeleteUser_Call {
	return &MockUserRepository_DeleteUser_Call{Call: _e.mock.On("DeleteUser", ctx, id)}
}

func (_c *MockUserRepository_DeleteUser_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_DeleteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) Return(err error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_DeleteUser_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockUserRepository_DeleteUser_Call {
	_c.Call.Return(run)
	return _c
}

// Follow provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Follow(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) error {
	ret := _mock.Called(ctx, followedByUserId, followingUserId)

	if len(ret) == 0 {
		panic("no return value specified for Follow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, followedByUserId, followingUserId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Follow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Follow'
type MockUserRepository_Follow_Call struct {
	*mock.Call
}

// Follow is a helper method to define mock.On call
//   - ctx context.Context
//   - followedByUserId uuid.UUID
//   - followingUserId uuid.UUID
func (_e *MockUserRepository_Expecter) Follow(ctx interface{}, followedByUserId interface{}, followingUserId interface{}) *MockUserRepository_Follow_Call {
	return &MockUserRepository_Follow_Call{Call: _e.mock.On("Follow", ctx, followedByUserId, followingUserId)}
}

func (_c *MockUserRepository_Follow_Call) Run(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID)) *MockUserRepository_Follow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Follow_Call) Return(err error) *MockUserRepository_Follow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Follow_Call) RunAndReturn(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) error) *MockUserRepository_Follow_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByEmail(ctx context.Context, email string) (mo.Option[user_types.User], error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 mo.Option[user_types.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (mo.Option[user_types.User], error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) mo.Option[user_types.User]); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(mo.Option[user_types.User])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockUserRepository_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserRepository_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockUserRepository_GetUserByEmail_Call {
	return &MockUserRepository_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockUserRepository_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) Return(option mo.Option[user_types.User], err error) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(option, err)
	return _c
}

func (_c *MockUserRepository_GetUserByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (mo.Option[user_types.User], error)) *MockUserRepository_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserById provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserById(ctx context.Context, id uuid.UUID) (mo.Option[user_types.User], error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 mo.Option[user_types.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (mo.Option[user_types.User], error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) mo.Option[user_types.User]); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(mo.Option[user_types.User])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserById'
type MockUserRepository_GetUserById_Call struct {
	*mock.Call
}

// GetUserById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserRepository_Expecter) GetUserById(ctx interface{}, id interface{}) *MockUserRepository_GetUserById_Call {
	return &MockUserRepository_GetUserById_Call{Call: _e.mock.On("GetUserById", ctx, id)}
}

func (_c *MockUserRepository_GetUserById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserRepository_GetUserById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserById_Call) Return(option mo.Option[user_types.User], err error) *MockUserRepository_GetUserById_Call {
	_c.Call.Return(option, err)
	return _c
}

func (_c *MockUserRepository_GetUserById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (mo.Option[user_types.User], error)) *MockUserRepository_GetUserById_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByUsername provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetUserByUsername(ctx context.Context, username string) (mo.Option[user_types.User], error) {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 mo.Option[user_types.User]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (mo.Option[user_types.User], error)); ok {
		return returnFunc(ctx, username)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) mo.Option[user_types.User]); ok {
		r0 = returnFunc(ctx, username)
	} else {
		r0 = ret.Get(0).(mo.Option[user_types.User])
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, username)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetUserByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByUsername'
type MockUserRepository_GetUserByUsername_Call struct {
	*mock.Call
}

// GetUserByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserRepository_Expecter) GetUserByUsername(ctx interface{}, username interface{}) *MockUserRepository_GetUserByUsername_Call {
	return &MockUserRepository_GetUserByUsername_Call{Call: _e.mock.On("GetUserByUsername", ctx, username)}
}

func (_c *MockUserRepository_GetUserByUsername_Call) Run(run func(ctx context.Context, username string)) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetUserByUsername_Call) Return(option mo.Option[user_types.User], err error) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Return(option, err)
	return _c
}

func (_c *MockUserRepository_GetUserByUsername_Call) RunAndReturn(run func(ctx context.Context, username string) (mo.Option[user_types.User], error)) *MockUserRepository_GetUserByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// IsFollowing provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) IsFollowing(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, followedByUserId, followingUserId)

	if len(ret) == 0 {
		panic("no return value specified for IsFollowing")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, followedByUserId, followingUserId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, followedByUserId, followingUserId)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, followedByUserId, followingUserId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_IsFollowing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsFollowing'
type MockUserRepository_IsFollowing_Call struct {
	*mock.Call
}

// IsFollowing is a helper method to define mock.On call
//   - ctx context.Context
//   - followedByUserId uuid.UUID
//   - followingUserId uuid.UUID
func (_e *MockUserRepository_Expecter) IsFollowing(ctx interface{}, followedByUserId interface{}, followingUserId interface{}) *MockUserRepository_IsFollowing_Call {
	return &MockUserRepository_IsFollowing_Call{Call: _e.mock.On("IsFollowing", ctx, followedByUserId, followingUserId)}
}

func (_c *MockUserRepository_IsFollowing_Call) Run(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID)) *MockUserRepository_IsFollowing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_IsFollowing_Call) Return(b bool, err error) *MockUserRepository_IsFollowing_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_IsFollowing_Call) RunAndReturn(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) (bool, error)) *MockUserRepository_IsFollowing_Call {
	_c.Call.Return(run)
	return _c
}

// Unfollow provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Unfollow(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) error {
	ret := _mock.Called(ctx, followedByUserId, followingUserId)

	if len(ret) == 0 {
		panic("no return value specified for Unfollow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, followedByUserId, followingUserId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_Unfollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unfollow'
type MockUserRepository_Unfollow_Call struct {
	*mock.Call
}

// Unfollow is a helper method to define mock.On call
//   - ctx context.Context
//   - followedByUserId uuid.UUID
//   - followingUserId uuid.UUID
func (_e *MockUserRepository_Expecter) Unfollow(ctx interface{}, followedByUserId interface{}, followingUserId interface{}) *MockUserRepository_Unfollow_Call {
	return &MockUserRepository_Unfollow_Call{Call: _e.mock.On("Unfollow", ctx, followedByUserId, followingUserId)}
}

func (_c *MockUserRepository_Unfollow_Call) Run(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID)) *MockUserRepository_Unfollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserRepository_Unfollow_Call) Return(err error) *MockUserRepository_Unfollow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_Unfollow_Call) RunAndReturn(run func(ctx context.Context, followedByUserId uuid.UUID, followingUserId uuid.UUID) error) *MockUserRepository_Unfollow_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) UpsertUser(ctx context.Context, user user_types.User) (user_types.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpsertUser")
	}

	var r0 user_types.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user_types.User) (user_types.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, user_types.User) user_types.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(user_types.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, user_types.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_UpsertUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertUser'
type MockUserRepository_UpsertUser_Call struct {
	*mock.Call
}

// UpsertUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user user_types.User
func (_e *MockUserRepository_Expecter) UpsertUser(ctx interface{}, user interface{}) *MockUserRepository_UpsertUser_Call {
	return &MockUserRepository_UpsertUser_Call{Call: _e.mock.On("UpsertUser", ctx, user)}
}

func (_c *MockUserRepository_UpsertUser_Call) Run(run func(ctx context.Context, user user_types.User)) *MockUserRepository_UpsertUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user_types.User
		if args[1] != nil {
			arg1 = args[1].(user_types.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_UpsertUser_Call) Return(user1 user_types.User, err error) *MockUserRepository_UpsertUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_UpsertUser_Call) RunAndReturn(run func(ctx context.Context, user user_types.User) (user_types.User, error)) *MockUserRepository_UpsertUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserValidations creates a new instance of MockUserValidations. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserValidations(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserValidations {
	mock := &MockUserValidations{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserValidations is an autogenerated mock type for the UserValidations type
type MockUserValidations struct {
	mock.Mock
}

type MockUserValidations_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserValidations) EXPECT() *MockUserValidations_Expecter {
	return &MockUserValidations_Expecter{mock: &_m.Mock}
}

// ValidateCanFollow provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateCanFollow(followedByUserId uuid.UUID, followingUserId uuid.UUID) user_types.DomainError {
	ret := _mock.Called(followedByUserId, followingUserId)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCanFollow")
	}

	var r0 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID, uuid.UUID) user_types.DomainError); ok {
		r0 = returnFunc(followedByUserId, followingUserId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user_types.DomainError)
		}
	}
	return r0
}

// MockUserValidations_ValidateCanFollow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCanFollow'
type MockUserValidations_ValidateCanFollow_Call struct {
	*mock.Call
}

// ValidateCanFollow is a helper method to define mock.On call
//   - followedByUserId uuid.UUID
//   - followingUserId uuid.UUID
func (_e *MockUserValidations_Expecter) ValidateCanFollow(followedByUserId interface{}, followingUserId interface{}) *MockUserValidations_ValidateCanFollow_Call {
	return &MockUserValidations_ValidateCanFollow_Call{Call: _e.mock.On("ValidateCanFollow", followedByUserId, followingUserId)}
}

func (_c *MockUserValidations_ValidateCanFollow_Call) Run(run func(followedByUserId uuid.UUID, followingUserId uuid.UUID)) *MockUserValidations_ValidateCanFollow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateCanFollow_Call) Return(domainError user_types.DomainError) *MockUserValidations_ValidateCanFollow_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockUserValidations_ValidateCanFollow_Call) RunAndReturn(run func(followedByUserId uuid.UUID, followingUserId uuid.UUID) user_types.DomainError) *MockUserValidations_ValidateCanFollow_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateEmailDoesNotConflict provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateEmailDoesNotConflict(ctx context.Context, email string) user_types.DomainError {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ValidateEmailDoesNotConflict")
	}

	var r0 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user_types.DomainError); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user_types.DomainError)
		}
	}
	return r0
}

// MockUserValidations_ValidateEmailDoesNotConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateEmailDoesNotConflict'
type MockUserValidations_ValidateEmailDoesNotConflict_Call struct {
	*mock.Call
}

// ValidateEmailDoesNotConflict is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserValidations_Expecter) ValidateEmailDoesNotConflict(ctx interface{}, email interface{}) *MockUserValidations_ValidateEmailDoesNotConflict_Call {
	return &MockUserValidations_ValidateEmailDoesNotConflict_Call{Call: _e.mock.On("ValidateEmailDoesNotConflict", ctx, email)}
}

func (_c *MockUserValidations_ValidateEmailDoesNotConflict_Call) Run(run func(ctx context.Context, email string)) *MockUserValidations_ValidateEmailDoesNotConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateEmailDoesNotConflict_Call) Return(domainError user_types.DomainError) *MockUserValidations_ValidateEmailDoesNotConflict_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockUserValidations_ValidateEmailDoesNotConflict_Call) RunAndReturn(run func(ctx context.Context, email string) user_types.DomainError) *MockUserValidations_ValidateEmailDoesNotConflict_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUser provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateUser(user user_types.User) user_types.DomainError {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUser")
	}

	var r0 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(user_types.User) user_types.DomainError); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user_types.DomainError)
		}
	}
	return r0
}

// MockUserValidations_ValidateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUser'
type MockUserValidations_ValidateUser_Call struct {
	*mock.Call
}

// ValidateUser is a helper method to define mock.On call
//   - user user_types.User
func (_e *MockUserValidations_Expecter) ValidateUser(user interface{}) *MockUserValidations_ValidateUser_Call {
	return &MockUserValidations_ValidateUser_Call{Call: _e.mock.On("ValidateUser", user)}
}

func (_c *MockUserValidations_ValidateUser_Call) Run(run func(user user_types.User)) *MockUserValidations_ValidateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user_types.User
		if args[0] != nil {
			arg0 = args[0].(user_types.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateUser_Call) Return(domainError user_types.DomainError) *MockUserValidations_ValidateUser_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockUserValidations_ValidateUser_Call) RunAndReturn(run func(user user_types.User) user_types.DomainError) *MockUserValidations_ValidateUser_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUserIdExists provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateUserIdExists(ctx context.Context, id uuid.UUID) (user_types.User, user_types.DomainError) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUserIdExists")
	}

	var r0 user_types.User
	var r1 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (user_types.User, user_types.DomainError)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) user_types.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(user_types.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) user_types.DomainError); ok {
		r1 = returnFunc(ctx, id)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(user_types.DomainError)
		}
	}
	return r0, r1
}

// MockUserValidations_ValidateUserIdExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUserIdExists'
type MockUserValidations_ValidateUserIdExists_Call struct {
	*mock.Call
}

// ValidateUserIdExists is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockUserValidations_Expecter) ValidateUserIdExists(ctx interface{}, id interface{}) *MockUserValidations_ValidateUserIdExists_Call {
	return &MockUserValidations_ValidateUserIdExists_Call{Call: _e.mock.On("ValidateUserIdExists", ctx, id)}
}

func (_c *MockUserValidations_ValidateUserIdExists_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockUserValidations_ValidateUserIdExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateUserIdExists_Call) Return(user user_types.User, domainError user_types.DomainError) *MockUserValidations_ValidateUserIdExists_Call {
	_c.Call.Return(user, domainError)
	return _c
}

func (_c *MockUserValidations_ValidateUserIdExists_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (user_types.User, user_types.DomainError)) *MockUserValidations_ValidateUserIdExists_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUsernameDoesNotConflict provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateUsernameDoesNotConflict(ctx context.Context, username string) user_types.DomainError {
	ret := _mock.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUsernameDoesNotConflict")
	}

	var r0 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user_types.DomainError); ok {
		r0 = returnFunc(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(user_types.DomainError)
		}
	}
	return r0
}

// MockUserValidations_ValidateUsernameDoesNotConflict_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUsernameDoesNotConflict'
type MockUserValidations_ValidateUsernameDoesNotConflict_Call struct {
	*mock.Call
}

// ValidateUsernameDoesNotConflict is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *MockUserValidations_Expecter) ValidateUsernameDoesNotConflict(ctx interface{}, username interface{}) *MockUserValidations_ValidateUsernameDoesNotConflict_Call {
	return &MockUserValidations_ValidateUsernameDoesNotConflict_Call{Call: _e.mock.On("ValidateUsernameDoesNotConflict", ctx, username)}
}

func (_c *MockUserValidations_ValidateUsernameDoesNotConflict_Call) Run(run func(ctx context.Context, username string)) *MockUserValidations_ValidateUsernameDoesNotConflict_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateUsernameDoesNotConflict_Call) Return(domainError user_types.DomainError) *MockUserValidations_ValidateUsernameDoesNotConflict_Call {
	_c.Call.Return(domainError)
	return _c
}

func (_c *MockUserValidations_ValidateUsernameDoesNotConflict_Call) RunAndReturn(run func(ctx context.Context, username string) user_types.DomainError) *MockUserValidations_ValidateUsernameDoesNotConflict_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateUsernameExists provides a mock function for the type MockUserValidations
func (_mock *MockUserValidations) ValidateUsernameExists(ctx context.Context, email string) (user_types.User, user_types.DomainError) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for ValidateUsernameExists")
	}

	var r0 user_types.User
	var r1 user_types.DomainError
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (user_types.User, user_types.DomainError)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) user_types.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		r0 = ret.Get(0).(user_types.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) user_types.DomainError); ok {
		r1 = returnFunc(ctx, email)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(user_types.DomainError)
		}
	}
	return r0, r1
}

// MockUserValidations_ValidateUsernameExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateUsernameExists'
type MockUserValidations_ValidateUsernameExists_Call struct {
	*mock.Call
}

// ValidateUsernameExists is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockUserValidations_Expecter) ValidateUsernameExists(ctx interface{}, email interface{}) *MockUserValidations_ValidateUsernameExists_Call {
	return &MockUserValidations_ValidateUsernameExists_Call{Call: _e.mock.On("ValidateUsernameExists", ctx, email)}
}

func (_c *MockUserValidations_ValidateUsernameExists_Call) Run(run func(ctx context.Context, email string)) *MockUserValidations_ValidateUsernameExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserValidations_ValidateUsernameExists_Call) Return(user user_types.User, domainError user_types.DomainError) *MockUserValidations_ValidateUsernameExists_Call {
	_c.Call.Return(user, domainError)
	return _c
}

func (_c *MockUserValidations_ValidateUsernameExists_Call) RunAndReturn(run func(ctx context.Context, email string) (user_types.User, user_types.DomainError)) *MockUserValidations_ValidateUsernameExists_Call {
	_c.Call.Return(run)
	return _c
}
